    function buildLatexDocument() {
      const title = escapeLatexText(getDocumentTitleFromMarkdown());
      const body = markdownToLatexBody(expandEmbeddedImages(editor.value));
      return String.raw`% Generated by ScienceMD
\documentclass[11pt,a4paper]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage{amsmath,amssymb}
\usepackage{graphicx}
\usepackage{booktabs}
\usepackage{array}
\usepackage{tabularx}
\usepackage{hyperref}
\usepackage[margin=1in]{geometry}
\usepackage{enumitem}
\usepackage{xcolor}
\usepackage{listings}
\usepackage{float}
\hypersetup{hidelinks}
\setlength{\parindent}{0pt}
\setlength{\parskip}{0.7em}
\title{${title}}
\author{}
\date{}

\begin{document}
\maketitle

${body}

\end{document}
`;
    }

    function downloadLatex(fileNameOverride = null) {
      const safeName = normaliseLatexFileName(fileNameOverride || currentFileName || 'science-draft.tex');
      downloadTextFile(buildLatexDocument(), safeName, 'application/x-tex;charset=utf-8');
      showToast(`Saved ${safeName}`);
    }

